name: resistify
channels:
 - pytorch
 - conda-forge
 - bioconda
dependencies:
 - python>=3.9,<3.10
 - scikit-learn==0.24.2
 - cython<3
 - numpy < 1.23.0
 - biopython
 - rich
 - rich-argparse
 - pytorch 
 - torchvision 
 - torchaudio 
 - cpuonly
 - fair-esm
 - transformers==4.31.0
 - sentencepiece